In [ ]:
BASE_PATH = "."

In [2]:
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
import random
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#import tensorflow as tf

In [4]:
RANDOM_SEED = 1234

random.seed(RANDOM_SEED)
np.random.seed(RANDOM_SEED)
#tf.random.set_seed(RANDOM_SEED)

In [5]:
PCA_COMPONENTS = 8

In [6]:
df_tr_day_syn_resampled = pd.read_csv(BASE_PATH + "/dataset/tr_day_syn.csv")

In [7]:
df_test_day_syn_resampled = pd.read_csv(BASE_PATH + "/dataset/test_day_syn.csv")

In [8]:
df_tr_day_syn_resampled_small = pd.read_csv(BASE_PATH + "/dataset/tr_day_syn_small.csv")

In [9]:
df_test_day_syn_resampled_small = pd.read_csv(BASE_PATH + "/dataset/test_day_syn_small.csv")

In [10]:
df_tr_day_syn_resampled_tiny = pd.read_csv(BASE_PATH + "/dataset/tr_day_syn_tiny.csv")

In [11]:
df_test_day_syn_resampled_tiny = pd.read_csv(BASE_PATH + "/dataset/test_day_syn_tiny.csv")

In [12]:
x_tr = df_tr_day_syn_resampled.drop(columns = " Label").to_numpy()

In [13]:
np.shape(x_tr)

(80000, 79)

In [14]:
y_tr = df_tr_day_syn_resampled[" Label"].to_numpy()

In [15]:
np.shape(y_tr)

(80000,)

In [16]:
x_test = df_test_day_syn_resampled.drop(columns = " Label").to_numpy()

In [17]:
np.shape(x_test)

(20000, 79)

In [18]:
y_test = df_test_day_syn_resampled[" Label"].to_numpy()

In [19]:
np.shape(y_test)

(20000,)

In [20]:
x_tr_small = df_tr_day_syn_resampled_small.drop(columns = " Label").to_numpy()

In [21]:
np.shape(x_tr_small)

(800, 79)

In [22]:
y_tr_small = df_tr_day_syn_resampled_small[" Label"].to_numpy()

In [23]:
np.shape(y_tr_small)

(800,)

In [24]:
x_test_small = df_test_day_syn_resampled_small.drop(columns = " Label").to_numpy()

In [25]:
np.shape(x_test_small)

(200, 79)

In [26]:
y_test_small = df_test_day_syn_resampled_small[" Label"].to_numpy()

In [27]:
np.shape(y_test_small)

(200,)

In [28]:
x_tr_tiny = df_tr_day_syn_resampled_tiny.drop(columns = " Label").to_numpy()

In [29]:
np.shape(x_tr_tiny)

(80, 79)

In [30]:
y_tr_tiny = df_tr_day_syn_resampled_tiny[" Label"].to_numpy()

In [31]:
np.shape(y_tr_tiny)

(80,)

In [32]:
x_test_tiny = df_test_day_syn_resampled_tiny.drop(columns = " Label").to_numpy()

In [33]:
np.shape(x_test_tiny)

(20, 79)

In [34]:
y_test_tiny = df_test_day_syn_resampled_tiny[" Label"].to_numpy()

In [35]:
np.shape(y_test_tiny)

(20,)

In [36]:
from sklearn.model_selection import train_test_split

In [37]:
x_val, x_test, y_val, y_test = train_test_split(x_test, y_test, train_size = 0.5, stratify = y_test)

In [38]:
unique, counts = np.unique(y_test, return_counts = True)
dict(zip(unique, counts))

{0: 9000, 1: 1000}

In [39]:
unique, counts = np.unique(y_val, return_counts = True)
dict(zip(unique, counts))

{0: 9000, 1: 1000}

In [40]:
x_val_small, x_test_small, y_val_small, y_test_small = train_test_split(x_test_small, y_test_small, train_size = 0.5, stratify = y_test_small)

In [41]:
unique, counts = np.unique(y_test_small, return_counts = True)
dict(zip(unique, counts))

{0: 90, 1: 10}

In [42]:
unique, counts = np.unique(y_val_small, return_counts = True)
dict(zip(unique, counts))

{0: 90, 1: 10}

In [43]:
x_val_tiny, x_test_tiny, y_val_tiny, y_test_tiny = train_test_split(x_test_tiny, y_test_tiny, train_size = 0.5, stratify = y_test_tiny)

In [44]:
unique, counts = np.unique(y_test_tiny, return_counts = True)
dict(zip(unique, counts))

{0: 9, 1: 1}

In [45]:
unique, counts = np.unique(y_val_tiny, return_counts = True)
dict(zip(unique, counts))

{0: 9, 1: 1}

In [46]:
from sklearn.preprocessing import MaxAbsScaler

In [47]:
scaler = MaxAbsScaler()
x_tr = scaler.fit_transform(x_tr)

x_test = scaler.transform(x_test)
x_val = scaler.transform(x_val)

In [48]:
x_test = np.clip(x_test, 0, 1)
x_val = np.clip(x_val, 0, 1)

In [49]:
scaler = MaxAbsScaler()
x_tr_small = scaler.fit_transform(x_tr_small)

x_test_small = scaler.transform(x_test_small)
x_val_small = scaler.transform(x_val_small)

In [50]:
x_test_small = np.clip(x_test_small, 0, 1)
x_val_small = np.clip(x_val_small, 0, 1)

In [51]:
scaler = MaxAbsScaler()
x_tr_tiny = scaler.fit_transform(x_tr_tiny)

x_test_tiny = scaler.transform(x_test_tiny)
x_val_tiny = scaler.transform(x_val_tiny)

In [52]:
x_test_tiny = np.clip(x_test_tiny, 0, 1)
x_val_tiny = np.clip(x_val_tiny, 0, 1)

In [53]:
from sklearn.decomposition import PCA

In [54]:
pca = PCA(n_components = 4)

In [55]:
xs_tr = pca.fit_transform(x_tr)
xs_test = pca.transform(x_test)
xs_val = pca.transform(x_val)

In [56]:
pca.explained_variance_ratio_

array([0.49471005, 0.14794817, 0.09526188, 0.0757135 ])

In [57]:
np.cumsum(pca.explained_variance_ratio_)

array([0.49471005, 0.64265822, 0.7379201 , 0.81363359])

In [58]:
xs_tr_small = pca.fit_transform(x_tr_small)
xs_test_small = pca.transform(x_test_small)
xs_val_small = pca.transform(x_val_small)

In [59]:
pca.explained_variance_ratio_

array([0.46562012, 0.13212018, 0.08235013, 0.07208547])

In [60]:
np.cumsum(pca.explained_variance_ratio_)

array([0.46562012, 0.5977403 , 0.68009042, 0.75217589])

In [61]:
xs_tr_tiny = pca.fit_transform(x_tr_tiny)
xs_test_tiny = pca.transform(x_test_tiny)
xs_val_tiny = pca.transform(x_val_tiny)

In [62]:
pca.explained_variance_ratio_

array([0.43591813, 0.14743916, 0.12489812, 0.06756595])

In [63]:
np.cumsum(pca.explained_variance_ratio_)

array([0.43591813, 0.58335729, 0.70825541, 0.77582136])

In [64]:
pca = PCA(n_components = 8)

In [65]:
xs_tr = pca.fit_transform(x_tr)
xs_test = pca.transform(x_test)
xs_val = pca.transform(x_val)

In [66]:
pca.explained_variance_ratio_

array([0.49471005, 0.14794817, 0.09526188, 0.0757135 , 0.05001996,
       0.03591552, 0.02761234, 0.01298894])

In [67]:
np.cumsum(pca.explained_variance_ratio_)

array([0.49471005, 0.64265822, 0.7379201 , 0.81363359, 0.86365355,
       0.89956907, 0.92718141, 0.94017035])

In [68]:
xs_tr_small = pca.fit_transform(x_tr_small)
xs_test_small = pca.transform(x_test_small)
xs_val_small = pca.transform(x_val_small)

In [69]:
pca.explained_variance_ratio_

array([0.46562012, 0.13212018, 0.08235013, 0.07208547, 0.06254231,
       0.04522041, 0.03242256, 0.02366509])

In [70]:
np.cumsum(pca.explained_variance_ratio_)

array([0.46562012, 0.5977403 , 0.68009042, 0.75217589, 0.8147182 ,
       0.85993861, 0.89236117, 0.91602626])

In [71]:
xs_tr_tiny = pca.fit_transform(x_tr_tiny)
xs_test_tiny = pca.transform(x_test_tiny)
xs_val_tiny = pca.transform(x_val_tiny)

In [72]:
pca.explained_variance_ratio_

array([0.43591813, 0.14743916, 0.12489812, 0.06756595, 0.06019821,
       0.04381756, 0.03385249, 0.02647354])

In [73]:
np.cumsum(pca.explained_variance_ratio_)

array([0.43591813, 0.58335729, 0.70825541, 0.77582136, 0.83601956,
       0.87983712, 0.91368961, 0.94016315])

In [74]:
pca = PCA(n_components = 16)

In [75]:
xs_tr = pca.fit_transform(x_tr)
xs_test = pca.transform(x_test)
xs_val = pca.transform(x_val)

In [76]:
pca.explained_variance_ratio_

array([0.49471005, 0.14794817, 0.09526188, 0.0757135 , 0.05001996,
       0.03591552, 0.02761234, 0.01298894, 0.01040956, 0.00884658,
       0.00554573, 0.00537861, 0.00383489, 0.00305403, 0.0028532 ,
       0.00263098])

In [77]:
np.cumsum(pca.explained_variance_ratio_)

array([0.49471005, 0.64265822, 0.7379201 , 0.81363359, 0.86365355,
       0.89956907, 0.92718141, 0.94017035, 0.95057991, 0.9594265 ,
       0.96497222, 0.97035083, 0.97418572, 0.97723975, 0.98009296,
       0.98272393])

In [78]:
xs_tr_small = pca.fit_transform(x_tr_small)
xs_test_small = pca.transform(x_test_small)
xs_val_small = pca.transform(x_val_small)

In [79]:
pca.explained_variance_ratio_

array([0.46562012, 0.13212018, 0.08235013, 0.07208547, 0.06254231,
       0.04522041, 0.03242256, 0.02366509, 0.01964514, 0.0148157 ,
       0.01011775, 0.00679155, 0.00528104, 0.00415444, 0.00380063,
       0.00284832])

In [80]:
np.cumsum(pca.explained_variance_ratio_)

array([0.46562012, 0.5977403 , 0.68009042, 0.75217589, 0.8147182 ,
       0.85993861, 0.89236117, 0.91602626, 0.93567139, 0.9504871 ,
       0.96060485, 0.96739639, 0.97267743, 0.97683188, 0.9806325 ,
       0.98348083])

In [81]:
xs_tr_tiny = pca.fit_transform(x_tr_tiny)
xs_test_tiny = pca.transform(x_test_tiny)
xs_val_tiny = pca.transform(x_val_tiny)

In [82]:
pca.explained_variance_ratio_

array([0.43591813, 0.14743916, 0.12489812, 0.06756595, 0.06019821,
       0.04381756, 0.03385249, 0.02647354, 0.02102161, 0.01080368,
       0.00748144, 0.00637917, 0.00429314, 0.00354136, 0.0023637 ,
       0.0017079 ])

In [83]:
np.cumsum(pca.explained_variance_ratio_)

array([0.43591813, 0.58335729, 0.70825541, 0.77582136, 0.83601956,
       0.87983712, 0.91368961, 0.94016315, 0.96118476, 0.97198844,
       0.97946988, 0.98584905, 0.9901422 , 0.99368355, 0.99604725,
       0.99775515])